version: "2"
services:
  # Applications
  grafana:
    image: grafana/grafana:latest
    container_name: prisms-grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana-storage:/var/lib/grafana
    environment:
      GF_SERVER_ROOT_URL: https://${GF_VIRTUAL_HOST}
    depends_on:
      - influxdb

  # Data storage
  influxdb:
    image: influxdb:1.6
    ports:
      - 8086:8086
    container_name: prisms-influxdb
    volumes:
      - ./influxdb-storage:/var/lib/influxdb
    environment:
      INFLUXDB_HTTP_AUTH_ENABLED: 'true'
